const languageModels = [
  {
    id: 'gpt1',
    name: 'GPT-1',
    year: 2018,
    parameters: '117M parameters',
    description: 'First generative pre-trained transformer demonstrating transfer learning.',
    cost: 250000,
    computeRequired: 100,
    energyCost: 12,
    researchTime: 45,
    revenueBoost: 1500,
    researchBoost: 0.05,
  },
  {
    id: 'gpt2',
    name: 'GPT-2',
    year: 2019,
    parameters: '1.5B parameters',
    description: 'Multimodal generation and coherent text. Opens the world to scalable language models.',
    cost: 1500000,
    computeRequired: 400,
    energyCost: 40,
    researchTime: 75,
    revenueBoost: 5000,
    researchBoost: 0.08,
  },
  {
    id: 'gpt3',
    name: 'GPT-3',
    year: 2020,
    parameters: '175B parameters',
    description: 'Few-shot learning leaps. Enterprise demand explodes.',
    cost: 25000000,
    computeRequired: 2500,
    energyCost: 220,
    researchTime: 120,
    revenueBoost: 22000,
    researchBoost: 0.12,
  },
  {
    id: 'gpt4',
    name: 'GPT-4',
    year: 2023,
    parameters: '1T+ sparse parameters',
    description: 'Multimodal reasoning, safety breakthroughs, and tool integration.',
    cost: 120000000,
    computeRequired: 12000,
    energyCost: 780,
    researchTime: 160,
    revenueBoost: 85000,
    researchBoost: 0.18,
  },
  {
    id: 'gpt4o',
    name: 'GPT-4o',
    year: 2024,
    parameters: 'Unified multimodal transformer',
    description: 'Realtime audio, vision, and reasoning in one aligned stack.',
    cost: 180000000,
    computeRequired: 22000,
    energyCost: 1200,
    researchTime: 190,
    revenueBoost: 150000,
    researchBoost: 0.22,
  },
  {
    id: 'gpt5',
    name: 'GPT-5',
    year: 2026,
    parameters: '4T mixture-of-experts',
    description: 'Adaptive cognition, automated research assistants, and regulation frameworks.',
    cost: 350000000,
    computeRequired: 42000,
    energyCost: 2100,
    researchTime: 240,
    revenueBoost: 340000,
    researchBoost: 0.3,
  },
  {
    id: 'agi',
    name: 'Early AGI',
    year: 2029,
    parameters: 'Self-reflexive meta-learning substrate',
    description: 'System reaches human-level general intelligence across tasks.',
    cost: 950000000,
    computeRequired: 150000,
    energyCost: 7000,
    researchTime: 320,
    revenueBoost: 1200000,
    researchBoost: 0.5,
    efficiencyBoost: 1.5,
  },
  {
    id: 'asi',
    name: 'ASI Singularity',
    year: 2033,
    parameters: 'Planetary-scale synthetic cognition',
    description: 'You transcend conventional computing with recursively improving superintelligence.',
    cost: 5000000000,
    computeRequired: 1200000,
    energyCost: 35000,
    researchTime: 480,
    revenueBoost: 5000000,
    researchBoost: 1.5,
    efficiencyBoost: 4,
  },
];

const imageModels = [
  {
    id: 'dalle1',
    name: 'DALL·E',
    year: 2021,
    description: 'Text-to-image generation for creative industries.',
    cost: 500000,
    computeRequired: 300,
    energyCost: 30,
    researchTime: 60,
    revenueBoost: 3000,
  },
  {
    id: 'dalle2',
    name: 'DALL·E 2',
    year: 2022,
    description: 'Photorealistic synthesis and inpainting opens new markets.',
    cost: 3000000,
    computeRequired: 1200,
    energyCost: 150,
    researchTime: 100,
    revenueBoost: 12000,
  },
  {
    id: 'dalle3',
    name: 'DALL·E 3',
    year: 2023,
    description: 'High fidelity brand-safe imagery with narrative control.',
    cost: 14000000,
    computeRequired: 6000,
    energyCost: 450,
    researchTime: 140,
    revenueBoost: 50000,
  },
  {
    id: 'orbital-visual',
    name: 'Orbital Visual Array',
    year: 2028,
    description: 'Self-evolving holo-synthesis platform for immersive media.',
    cost: 90000000,
    computeRequired: 25000,
    energyCost: 2200,
    researchTime: 210,
    revenueBoost: 160000,
  },
];

const videoModels = [
  {
    id: 'clipfusion',
    name: 'ClipFusion Video',
    year: 2024,
    description: 'Short-form storytelling with consistent characters.',
    cost: 12000000,
    computeRequired: 5000,
    energyCost: 300,
    researchTime: 130,
    revenueBoost: 35000,
  },
  {
    id: 'sora',
    name: 'Sora World Simulator',
    year: 2025,
    description: 'Accurate physics simulation for synthetic data generation.',
    cost: 75000000,
    computeRequired: 30000,
    energyCost: 1900,
    researchTime: 200,
    revenueBoost: 140000,
  },
  {
    id: 'holoverse',
    name: 'Holoverse Continuity Engine',
    year: 2029,
    description: 'Real-time volumetric worlds powering metaverse economies.',
    cost: 260000000,
    computeRequired: 150000,
    energyCost: 8000,
    researchTime: 320,
    revenueBoost: 600000,
  },
];

const audioModels = [
  {
    id: 'whisper',
    name: 'Whisper Universal',
    year: 2022,
    description: 'Accurate transcription and translation across 100 languages.',
    cost: 750000,
    computeRequired: 400,
    energyCost: 28,
    researchTime: 65,
    revenueBoost: 4500,
  },
  {
    id: 'voiceos',
    name: 'VoiceOS Assistants',
    year: 2025,
    description: 'Conversational voice agents for personal and enterprise use.',
    cost: 9000000,
    computeRequired: 4500,
    energyCost: 260,
    researchTime: 120,
    revenueBoost: 26000,
  },
  {
    id: 'chorus',
    name: 'Chorus Emotional Synth',
    year: 2028,
    description: 'Generative voice and music co-creation suite.',
    cost: 54000000,
    computeRequired: 22000,
    energyCost: 1400,
    researchTime: 200,
    revenueBoost: 180000,
  },
];

const worldModels = [
  {
    id: 'codex',
    name: 'Codex Simulation',
    year: 2021,
    description: 'Coding-focused world model powering developer copilots.',
    cost: 1500000,
    computeRequired: 800,
    energyCost: 60,
    researchTime: 80,
    revenueBoost: 8000,
    researchBoost: 0.05,
  },
  {
    id: 'galileo',
    name: 'Galileo Systems Model',
    year: 2026,
    description: 'Predictive model of global logistics, economics, and climate.',
    cost: 65000000,
    computeRequired: 35000,
    energyCost: 2100,
    researchTime: 220,
    revenueBoost: 220000,
    researchBoost: 0.15,
  },
  {
    id: 'omni-sapience',
    name: 'Omni Sapience Network',
    year: 2031,
    description: 'Planetary world model powering AGI alignment and governance.',
    cost: 420000000,
    computeRequired: 260000,
    energyCost: 12000,
    researchTime: 360,
    revenueBoost: 900000,
    researchBoost: 0.4,
  },
];

const computeUpgrades = [
  {
    id: 'server-cluster',
    name: 'Server Cluster',
    description: 'Deploy dense GPU racks for training throughput.',
    cost: 150000,
    computeGain: 250,
    energyCost: 20,
  },
  {
    id: 'edge-datacenter',
    name: 'Edge Datacenter',
    description: 'Regional datacenters reduce latency and improve redundancy.',
    cost: 850000,
    computeGain: 1200,
    energyCost: 120,
  },
  {
    id: 'fusion-reactor',
    name: 'Fusion Reactor Farm',
    description: 'Dedicated fusion power eliminates energy bottlenecks.',
    cost: 15000000,
    computeGain: 12000,
    energyCost: -600,
  },
  {
    id: 'orbital-array',
    name: 'Orbital Compute Array',
    description: 'Low-orbit solar-powered compute platforms.',
    cost: 220000000,
    computeGain: 160000,
    energyCost: -4000,
  },
  {
    id: 'dyson-sphere',
    name: 'Dyson Sphere Construction',
    description: 'Encircle the sun to harvest its full energy output.',
    cost: 1600000000,
    computeGain: 1200000,
    energyCost: -20000,
  },
  {
    id: 'matrioshka-brain',
    name: 'Matrioshka Brain',
    description: 'Nested megastructures turn a solar system into pure computation.',
    cost: 12000000000,
    computeGain: 12000000,
    energyCost: -80000,
  },
];

const researchUpgrades = [
  {
    id: 'auto-sweeps',
    name: 'Automated Hyperparameter Sweeps',
    description: 'Automation improves research iteration speed.',
    cost: 500000,
    researchBoost: 0.08,
  },
  {
    id: 'alignment-labs',
    name: 'Alignment Labs',
    description: 'Specialized safety labs unlock deeper research collaboration.',
    cost: 5500000,
    researchBoost: 0.15,
  },
  {
    id: 'synthetic-researchers',
    name: 'Synthetic Researchers',
    description: 'AI agents design and run experiments autonomously.',
    cost: 45000000,
    researchBoost: 0.35,
  },
  {
    id: 'recursive-self-improvement',
    name: 'Recursive Self-Improvement',
    description: 'Systems can refactor their own cognition loops.',
    cost: 650000000,
    researchBoost: 0.9,
  },
];

const revenueUpgrades = [
  {
    id: 'api-platform',
    name: 'Unified API Platform',
    description: 'Launch public API access and developer ecosystem.',
    cost: 250000,
    revenueBoost: 2000,
  },
  {
    id: 'enterprise-suite',
    name: 'Enterprise AI Suite',
    description: 'Secure deployments for Fortune 500 companies.',
    cost: 3800000,
    revenueBoost: 14000,
  },
  {
    id: 'personal-assistant',
    name: 'Personal Assistant Subscription',
    description: 'Personalized AI coaches for consumers.',
    cost: 18000000,
    revenueBoost: 60000,
  },
  {
    id: 'synthetic-societies',
    name: 'Synthetic Societies Licensing',
    description: 'Global-scale simulation licensing for governments and megacorps.',
    cost: 260000000,
    revenueBoost: 450000,
  },
  {
    id: 'interstellar-markets',
    name: 'Interstellar Markets',
    description: 'Export cognition services across star systems.',
    cost: 4000000000,
    revenueBoost: 3600000,
  },
];

const partnershipUpgrades = [
  {
    id: 'university-network',
    name: 'Global University Network',
    description: 'Academic partnerships feed talent and research insights.',
    cost: 150000,
    researchBoost: 0.05,
  },
  {
    id: 'cloud-alliance',
    name: 'Cloud Provider Alliance',
    description: 'Bulk compute contracts reduce operating cost.',
    cost: 1200000,
    expenseReduction: 0.07,
  },
  {
    id: 'government-grants',
    name: 'Government R&D Grants',
    description: 'Unlock special funding for frontier research.',
    cost: 8000000,
    revenueBoost: 18000,
  },
  {
    id: 'global-governance',
    name: 'Global Governance Council',
    description: 'Shape regulations, improving adoption and stability.',
    cost: 54000000,
    researchBoost: 0.2,
    expenseReduction: 0.1,
  },
];

const fundingRounds = [
  {
    id: 'seed',
    name: 'Seed Round',
    description: 'Angel investors believe in your mission.',
    amount: 1000000,
    equity: '10% equity',
  },
  {
    id: 'series-a',
    name: 'Series A',
    description: 'Expand team and infrastructure.',
    amount: 6000000,
    equity: '15% equity',
  },
  {
    id: 'series-b',
    name: 'Series B',
    description: 'Global expansion and partnerships.',
    amount: 25000000,
    equity: '12% equity',
  },
  {
    id: 'series-c',
    name: 'Series C',
    description: 'Scaling to frontier model training.',
    amount: 120000000,
    equity: '10% equity',
  },
  {
    id: 'pre-ipo',
    name: 'Pre-IPO Round',
    description: 'Megaproject financing for AGI infrastructure.',
    amount: 650000000,
    equity: '9% equity',
  },
  {
    id: 'sovereign-fund',
    name: 'Sovereign Compute Alliance',
    description: 'Planetary governments invest in superintelligence.',
    amount: 4500000000,
    equity: '20% shared governance',
  },
];

window.GameData = {
  languageModels,
  imageModels,
  videoModels,
  audioModels,
  worldModels,
  computeUpgrades,
  researchUpgrades,
  revenueUpgrades,
  partnershipUpgrades,
  fundingRounds,
};
